> ### **Assignment 2 - Numpy Array Operations** 
>
> This assignment is part of the course ["Data Analysis with Python: Zero to Pandas"](http://zerotopandas.com). The objective of this assignment is to develop a solid understanding of Numpy array operations. In this assignment you will:
> 
> 1. Pick 5 interesting Numpy array functions by going through the documentation: https://numpy.org/doc/stable/reference/routines.html 
> 2. Run and modify this Jupyter notebook to illustrate their usage (some explanation and 3 examples for each function). Use your imagination to come up with interesting and unique examples.
> 3. Upload this notebook to your Jovian profile using `jovian.commit` and make a submission here: https://jovian.ml/learn/data-analysis-with-python-zero-to-pandas/assignment/assignment-2-numpy-array-operations
> 4. (Optional) Share your notebook online (on Twitter, LinkedIn, Facebook) and on the community forum thread: https://jovian.ml/forum/t/assignment-2-numpy-array-operations-share-your-work/10575 . 
> 5. (Optional) Check out the notebooks [shared by other participants](https://jovian.ml/forum/t/assignment-2-numpy-array-operations-share-your-work/10575) and give feedback & appreciation.
>
> The recommended way to run this notebook is to click the "Run" button at the top of this page, and select "Run on Binder". This will run the notebook on mybinder.org, a free online service for running Jupyter notebooks.
>
> Try to give your notebook a catchy title & subtitle e.g. "All about Numpy array operations", "5 Numpy functions you didn't know you needed", "A beginner's guide to broadcasting in Numpy", "Interesting ways to create Numpy arrays", "Trigonometic functions in Numpy", "How to use Python for Linear Algebra" etc.
>
> **NOTE**: Remove this block of explanation text before submitting or sharing your notebook online - to make it more presentable.


# 5 numpy funcions


Numpy is a python library used for array manipulation. Working with array with normal python function have bigger time complexity than numpy functions. 

- np.atleast_2d()
- np.concatenate()
- numpy.ndarray.T
- np.left_shift()
- np.sort()


In [1]:
!pip install jovian --upgrade -q

In [2]:
import jovian

In [3]:
jovian.commit(project='numpy-array-operations')

<IPython.core.display.Javascript object>

[jovian] Updating notebook "khasrul/numpy-array-operations" on https://jovian.ai
[jovian] Committed successfully! https://jovian.ai/khasrul/numpy-array-operations


'https://jovian.ai/khasrul/numpy-array-operations'

Let's begin by importing Numpy and listing out the functions covered in this notebook.

In [4]:
import numpy as np

In [90]:
# List of functions explained 
function1 = np.atleast_2d()
function2 = np.concatenate()
function3 = numpy.ndarray.T
function4 = np.left_shift()
function5 = np.sort()

TypeError: concatenate() missing 1 required positional argument: 'arrays'

# Function 1 - np.atleast_2d()

When we pass a list or multiple lists on this function this will return them changing their dimension atleast by 2d

In [11]:
# Example 1 - single argument
a = np.ones(10,dtype=int)
b= np.atleast_2d(a)
print("'a' dimension:",a.ndim)
print("'b' dimension:",b.ndim)

'a' dimension: 1
'b' dimension: 2


A 1-d list is inputed and in output we get that list in 2-d format

In [21]:
# Example 2
a = np.random.randint(1,50,(3,3),dtype=int)
print(a,end='\n\n')
b,c,d = np.atleast_2d(a[:,0],a[:,1],a[:,2])
print(b,c,d)

[[11  1  6]
 [23  3  9]
 [ 5 28 11]]

[[11 23  5]] [[ 1  3 28]] [[ 6  9 11]]


Passed 2 lists as parameter, each of them converted to 2-d arrays

In [27]:
# Example 3 - breaking (to illustrate when it breaks)
a = np.random.randint(1,50,(3,3),dtype=int)
print(a,end='\n\n')
b,c= np.atleast_2d(a)
print(b)

[[36 35 14]
 [42  1 14]
 [21 10 28]]



ValueError: too many values to unpack (expected 2)

This function is returning 3 row as output, but we are assigning the results in 2 container. 

When a multidimensional array is inputed in np.atleast_2d() we can get rows as output, only if result is assigned in appropriate number of output container.

In [ ]:
jovian.commit()

## Function 2 - np.concatenate()

concatenate arrays along axises

In [47]:
# Example 1 - working
a = np.array([[1,2,3],[4,5,6]])
b= np.ones((1,3),dtype=int)

print(a)
print('\n')
print(b)
print('\n')

c = np.concatenate((a,b),axis=0)
c

[[1 2 3]
 [4 5 6]]


[[1 1 1]]




array([[1, 2, 3],
       [4, 5, 6],
       [1, 1, 1]])

Row wise concatenation

In [50]:
# Example 2 - working
a = np.array([[1,2,3],[4,5,6]])
b= np.ones((2,1),dtype=int)

print(a)
print('\n')
print(b)
print('\n')

c = np.concatenate((a,b),axis=1)
c

[[1 2 3]
 [4 5 6]]


[[1]
 [1]]




array([[1, 2, 3, 1],
       [4, 5, 6, 1]])

Column wise concatenation

In [51]:
# Example 3 - breaking (to illustrate when it breaks)
# Example 2 - working
a = np.array([[1,2,3],[4,5,6]])
b= np.ones((3,1),dtype=int)

print(a)
print('\n')
print(b)
print('\n')

c = np.concatenate((a,b),axis=1)
c

[[1 2 3]
 [4 5 6]]


[[1]
 [1]
 [1]]




ValueError: all the input array dimensions for the concatenation axis must match exactly, but along dimension 0, the array at index 0 has size 2 and the array at index 1 has size 3

For concatenating dimension have to match, where we are trying to concatenate column where a array having 3 row with a array of 2 rows

Some closing comments about when to use this function.

In [ ]:
jovian.commit()

## Function 3 - numpy.ndarray.T

Create transpose of any array (column become row and row become column)

In [54]:
# Example 1 - working
a = np.random.randint(1,100,size=(3,2))
print(a)
print('\n')
print(a.T)

[[35 50]
 [65 98]
 [42 81]]


[[35 65 42]
 [50 98 81]]


Making a 3X2 matrix to 2X3 transpose matrix

In [55]:
# Example 2 - working
a = np.random.randint(1,100,size=(2,3))
print(a)
print('\n')
print(a.T)

[[ 7 46 50]
 [13 98 67]]


[[ 7 13]
 [46 98]
 [50 67]]


Making a 2X3 matrix to 3X2 transpose matrix

In [59]:
# Example 3 - breaking (to illustrate when it breaks)
a = np.ones(5,dtype=int)

print(a,a.T,sep='\n')

[1 1 1 1 1]
[1 1 1 1 1]


here initial matrix and transpose matrix both are same, because to make a matrix to its transpose, initial matrix have to have same number of dimension to its transpose.

Very useful function

In [ ]:
jovian.commit()

## Function 4 - np.left_shift()

Bit wise shift operation

In [73]:
# Example 1 - working
a= np.binary_repr(6)
print(a)
b= np.left_shift(6,1)
print(b)


110
12


single time shifting

In [77]:
# Example 2 - working
a= np.binary_repr(6)
print(a)
b= np.left_shift(6,[2,1,3])
print(b)

110


ValueError: operands could not be broadcast together with shapes (2,) (3,) 

Shift multiple time and get answer as a list

In [78]:
# Example 3 - breaking (to illustrate when it breaks)
a= np.binary_repr(6)
print(a)
b= np.left_shift([6,7],[1,2,3])
print(b)

110
[24 28]


Any argument of have to be single integer or both have to be list of same size

Though bit wise operation is faster than others so this function will be very beneficial

In [ ]:
jovian.commit()

## Function 5 - np.sort()

Used for sorting numpy array

In [86]:
# Example 1 - working
a = np.random.randint(100,size=10)
print(a)
print('\n')
b=np.sort(a)
print(b)

[94 46 22 60  5  6 48 70 44 35]


[ 5  6 22 35 44 46 48 60 70 94]


Sort 1d array

In [88]:
# Example 2 - working
a = np.random.randint(100,size=(4,2))
print(a)
print('\n')
b=np.sort(a)
print(b)

[[49 36]
 [67 14]
 [94 72]
 [16 67]]


[[36 49]
 [14 67]
 [72 94]
 [16 67]]


if specific row or column is not defined to be sort then element of every row will be sorted

In [89]:
# Example 3 - breaking (to illustrate when it breaks)
a = np.random.randint(100,size=(4,2))
print(a)
print('\n')
sort(a)
print(a)

[[78 60]
 [57 85]
 [39 26]
 [47 15]]




NameError: name 'sort' is not defined

sort() this command doesn't work, we have to use np.sort()

In [ ]:
jovian.commit()

## Conclusion

The total number of numpy library is huge, all of them saves our time. But remembering all of them is very very tough.

## Reference Links
Provide links to your references and other interesting articles about Numpy arrays:
* Numpy official tutorial : https://numpy.org/doc/stable/user/quickstart.html
* ...

In [ ]:
jovian.commit()